# Generated by Django 5.1.1 on 2024-11-08 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_post_image_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 14, 18, 40, 132887)),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_avatars/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/community_icons/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 8, 14, 18, 40, 132887)),
        ),
    ]
