# Generated by Django 5.1.1 on 2024-11-13 09:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_postlike_date_time_user_avatar_alter_community_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 13, 10, 25, 49, 947771)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 10, 25, 49, 948771)),
        ),
    ]
