# Generated by Django 5.1.4 on 2024-12-28 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_remove_post_likes_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 13, 15, 37, 442050)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 28, 13, 15, 37, 441052)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 13, 15, 37, 443046)),
        ),
    ]
