# Generated by Django 5.0.3 on 2024-12-11 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_remove_post_likes_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 0, 43, 18, 802199)),
        ),
        migrations.AlterField(
            model_name='community',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 23, 43, 18, 802199, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 12, 0, 43, 18, 802199)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 0, 43, 18, 802199)),
        ),
    ]
