# Generated by Django 5.0.3 on 2025-01-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_alter_comment_date_alter_post_pub_date_and_more'),
        ('Base', '0009_alter_comment_date_alter_community_date_and_more'),
    ]

    operations = [
    ]
