# Generated by Django 5.0.3 on 2025-01-07 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_merge_20250107_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 10, 57, 5, 441168)),
        ),
        migrations.AlterField(
            model_name='community',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 9, 57, 5, 440168, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 7, 10, 57, 5, 441168)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 10, 57, 5, 441168)),
        ),
    ]
