# Generated by Django 5.0.3 on 2025-01-07 10:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_alter_comment_date_alter_community_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 11, 24, 11, 331499)),
        ),
        migrations.AlterField(
            model_name='community',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 10, 24, 11, 330499, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 7, 11, 24, 11, 330499)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 11, 24, 11, 331499)),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2025, 1, 7, 11, 24, 11, 331499))),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Base.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_comment_like'),
        ),
    ]
